import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-content-center h-screen text-4xl font-thin ">
         <p> We have the best <span className='underline'><Link href="/products" >products</Link></span></p>
      </main>

      
    </div>
  )
}
